list_of_occupations = list_of_occupations = ['Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Analyst',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Statistician',
 'Statistician',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist']

medals_won = ['Silver',
 'Silver',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Bronze',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Silver',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Bronze',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Bronze',
 'Silver',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Bronze',
 'Silver',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Bronze',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Bronze',
 'Silver',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Bronze',
 'Silver',
 'Silver',
 'Gold',
 'Silver',
 'Bronze',
 'Bronze',
 'Bronze',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Bronze',
 'Bronze',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Bronze',
 'Silver',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Bronze',
 'Bronze',
 'Bronze',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Bronze',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Bronze',
 'Bronze',
 'Bronze',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Silver',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Bronze',
 'Gold',
 'Bronze',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Bronze',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Bronze',
 'Bronze',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Bronze',
 'Bronze',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Bronze',
 'Silver',
 'Silver',
 'Bronze',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Gold',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Bronze',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Bronze',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Gold',
 'Bronze',
 'Silver',
 'Silver',
 'Gold',
 'Silver',
 'Bronze',
 'Bronze',
 'Bronze',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Bronze',
 'Bronze',
 'Silver',
 'Gold',
 'Bronze',
 'Bronze',
 'Bronze',
 'Bronze',
 'Bronze',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Silver',
 'Silver',
 'Silver',
 'Bronze',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Bronze',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Bronze',
 'Bronze',
 'Bronze',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Bronze',
 'Bronze',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Gold',
 'Bronze',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Bronze',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Silver',
 'Bronze',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Silver',
 'Silver',
 'Bronze',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Bronze',
 'Bronze',
 'Bronze',
 'Bronze',
 'Silver',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Silver',
 'Gold',
 'Bronze',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Gold',
 'Bronze',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Bronze',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Gold',
 'Bronze',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Bronze',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Bronze',
 'Bronze',
 'Bronze',
 'Gold',
 'Bronze',
 'Bronze',
 'Bronze',
 'Bronze',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Bronze',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Bronze',
 'Silver',
 'Bronze',
 'Bronze',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Silver',
 'Bronze',
 'Gold',
 'Silver',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Silver',
 'Gold',
 'Bronze',
 'Bronze',
 'Silver',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Bronze',
 'Silver',
 'Bronze',
 'Bronze',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Silver',
 'Silver',
 'Bronze',
 'Gold',
 'Bronze',
 'Bronze',
 'Silver',
 'Silver',
 'Bronze',
 'Bronze',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Bronze',
 'Bronze',
 'Gold',
 'Silver',
 'Bronze',
 'Gold',
 'Bronze',
 'Bronze',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Bronze',
 'Bronze',
 'Silver',
 'Bronze',
 'Bronze',
 'Bronze',
 'Gold',
 'Bronze',
 'Bronze',
 'Silver',
 'Gold',
 'Bronze',
 'Gold',
 'Silver',
 'Gold',
 'Silver',
 'Silver',
 'Gold',
 'Gold',
 'Gold',
 'Bronze',
 'Gold',
 'Gold',
 'Silver',
 'Bronze',
 'Gold',
 'Gold',
 'Gold']